/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Auction } from "./Auction";
export type { CoffeeMarketplace } from "./CoffeeMarketplace";
export type { Product } from "./Product";
export type { Voting } from "./Voting";
